version: '3'

services:
    web:
      build: .
      ports:
        - "8000:8000"
      environment:
         DB_HOST: db
         DB_NAME: credit
         DB_USER: postgres
         DB_PASSWORD: postgres
      depends_on:
        - db
      
    
    db:
      image: postgres
      expose:
        - 5432
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         POSTGRES_DB: credit
      volumes:
        - db_data:/var/lib/postgresql/data

volumes:
  db_data:
